Update to use new `mutagen-compose` beta
humanmade/altis-local-server pull request #385
Opened 2021-11-29 10:30 UTC by roborourke

With Docker Compose v2 there is now a new Mutagen Compose command that works with it and promises to be much more robust. In order to function correctly users must have at least Mutagen Compose 0.13.0-beta3 and be using Docker Compose v2.

2021-11-29 13:33 UTC, shadyvb requested changes
LGTM, except a minor wording fix.

2021-11-29 13:33 UTC, shadyvb commented on docs/troubleshooting.md
> +Due to the variability of Docker Desktop, Docker Engine and Mutagen versions, and that Mutagen is still in beta you encounter some problems.
you _may_ encounter some problems ?

```suggestion
Due to the variability of Docker Desktop, Docker Engine and Mutagen versions, and that Mutagen is still in beta, you may encounter some problems.
```

2021-11-29 14:17 UTC, roborourke commented on docs/troubleshooting.md
> +Due to the variability of Docker Desktop, Docker Engine and Mutagen versions, and that Mutagen is still in beta you encounter some problems.
Pretty important wording fix! Ta

2021-11-30 21:53 UTC, shadyvb approved these changes

2021-12-01 10:04 UTC, merged