Add Afterburner support to Local Server
humanmade/altis-local-server pull request #634
Opened 2023-10-25 14:04 UTC by joehoyle

2023-10-25 14:21 UTC, mikelittle requested changes
Looks good. Just a typo in the docs. And a lint issue about quotes.

2023-10-25 14:21 UTC, mikelittle commented on docs/using-afterburner.md
> +If your project uses Afterburner in Altis Cloud, you can enabled it in Altis Local Service by setting the `altis.modules.local-server.afterburner` value to `true`:
"enable" not "enabled"

2023-10-25 14:55 UTC, joehoyle commented on docs/using-afterburner.md
> +If your project uses Afterburner in Altis Cloud, you can enabled it in Altis Local Service by setting the `altis.modules.local-server.afterburner` value to `true`:
Ah good catch! Fixed now

2023-10-25 16:16 UTC, mikelittle approved these changes
There's still a linter issue about double quotes vs single quotes, but otherwise, looks good to me

2023-10-27 04:11 UTC, jerico approved these changes

2023-11-02 19:28 UTC, merged